vim.api.nvim_set_keymap('i', '<C-Space>', 'compe#complete()', {noremap = true; silent = true; expr = true;})
vim.api.nvim_set_keymap('i', '<CR>', 'compe#confirm(luaeval("require \'nvim-autopairs\'.autopairs_cr()"))', {noremap = true; silent = true; expr = true;})
vim.api.nvim_set_keymap('i', '<C-e>', 'compe#close()', {noremap = true; silent = true; expr = true;})
vim.api.nvim_set_keymap('i', '<C-f>', 'compe#scroll({"delta": +4})', {noremap = true; silent = true; expr = true;})
vim.api.nvim_set_keymap('i', '<C-d>', 'compe#scroll({"delta": -4})', {noremap = true; silent = true; expr = true;})
